# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39dd39699ec771314b437c39a44aa1ae8c7579058c3dc47777e2e4830780aa12d1c7ed299503a1a9d0559e8900427e3f0e7f8c65893c2cfe3e8834accfed2d62

test:
  secret_key_base: 7b24c4e0f911f051cc9b255c70f16887d46c8d4a07cd4afe487775256cdc177947633c9686e911ed7ee0ff71241c878b4148eaf741cfe605c457ee295c7368eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
